package turtle

// radicals is a slice of all radicals with associated information. It is by
// default sorted by radical number.
//
// The following data has been generated using the genradical tool [1] to parse
// the table of radicals at Wikipedia [2]. Only minor manual alterations have
// been performed.
//
// [1]: github.com/mewmew/playground/turtle/cmd/genradical
// [2]: https://en.wikipedia.org/wiki/Kangxi_radical#Table_of_radicals
var radicals = []*Radical{
	&Radical{Num: 1, Rune: "一", AltRune: "", Strokes: 1, Pinyin: "yī", Hiragana: "いち", Romaji: "ichi", Meaning: "one", Freq: 42, Simplified: "", Examples: "七三丈不丘世"},
	&Radical{Num: 2, Rune: "丨", AltRune: "", Strokes: 1, Pinyin: "gǔn", Hiragana: "ぼう", Romaji: "bō", Meaning: "line", Freq: 21, Simplified: "", Examples: "中"},
	&Radical{Num: 3, Rune: "丶", AltRune: "", Strokes: 1, Pinyin: "zhǔ", Hiragana: "てん", Romaji: "ten", Meaning: "dot", Freq: 10, Simplified: "", Examples: "丸主"},
	&Radical{Num: 4, Rune: "丿", AltRune: "", Strokes: 1, Pinyin: "piě", Hiragana: "の", Romaji: "no", Meaning: "bend", Freq: 33, Simplified: "", Examples: "久之乎"},
	&Radical{Num: 5, Rune: "乙", AltRune: "(⺄, 乚)", Strokes: 1, Pinyin: "yǐ", Hiragana: "おつ", Romaji: "otsu", Meaning: "second", Freq: 42, Simplified: "", Examples: "九也"},
	&Radical{Num: 6, Rune: "亅", AltRune: "", Strokes: 1, Pinyin: "jué", Hiragana: "はねぼう", Romaji: "hanebō", Meaning: "hook", Freq: 19, Simplified: "", Examples: "了事"},
	&Radical{Num: 7, Rune: "二", AltRune: "", Strokes: 2, Pinyin: "èr", Hiragana: "に", Romaji: "ni", Meaning: "two", Freq: 29, Simplified: "", Examples: "五井些亞"},
	&Radical{Num: 8, Rune: "亠", AltRune: "", Strokes: 2, Pinyin: "tóu", Hiragana: "なべぶた", Romaji: "nabebuta", Meaning: "lid", Freq: 38, Simplified: "", Examples: "亡交京"},
	&Radical{Num: 9, Rune: "人", AltRune: "(亻)", Strokes: 2, Pinyin: "rén", Hiragana: "ひと", Romaji: "hito", Meaning: "human", Freq: 794, Simplified: "", Examples: "仁休位今"},
	&Radical{Num: 10, Rune: "儿", AltRune: "", Strokes: 2, Pinyin: "ér", Hiragana: "にんにょう", Romaji: " ninyō", Meaning: "legs", Freq: 52, Simplified: "", Examples: "兄元"},
	&Radical{Num: 11, Rune: "入", AltRune: "", Strokes: 2, Pinyin: "rù", Hiragana: "いる", Romaji: "iru", Meaning: "enter", Freq: 28, Simplified: "", Examples: "入全兩"},
	&Radical{Num: 12, Rune: "八", AltRune: "", Strokes: 2, Pinyin: "bā", Hiragana: "はちがしら", Romaji: "hachigashira", Meaning: "divide", Freq: 44, Simplified: "", Examples: "公六共兵"},
	&Radical{Num: 13, Rune: "冂", AltRune: "", Strokes: 2, Pinyin: "jiōng", Hiragana: "まきがまえ", Romaji: "makigamae", Meaning: "upside down box", Freq: 50, Simplified: "", Examples: "内再"},
	&Radical{Num: 14, Rune: "冖", AltRune: "", Strokes: 2, Pinyin: "mì", Hiragana: "わかんむり", Romaji: "wakanmuri", Meaning: "cover", Freq: 30, Simplified: "", Examples: "冗冠"},
	&Radical{Num: 15, Rune: "冫", AltRune: "", Strokes: 2, Pinyin: "bīng", Hiragana: "にすい", Romaji: "nisui", Meaning: "ice", Freq: 115, Simplified: "", Examples: "冬冶冷凍"},
	&Radical{Num: 16, Rune: "几", AltRune: "", Strokes: 2, Pinyin: "jī", Hiragana: "つくえ", Romaji: "tsukue", Meaning: "table", Freq: 38, Simplified: "", Examples: "凡"},
	&Radical{Num: 17, Rune: "凵", AltRune: "", Strokes: 2, Pinyin: "kǎn", Hiragana: "うけばこ", Romaji: "ukebako", Meaning: "container, open mouth", Freq: 23, Simplified: "", Examples: "凶出函"},
	&Radical{Num: 18, Rune: "刀", AltRune: "(刂)", Strokes: 2, Pinyin: "dāo", Hiragana: "かたな", Romaji: "katana", Meaning: "knife, sword", Freq: 377, Simplified: "", Examples: "刀分切初利刻則前"},
	&Radical{Num: 19, Rune: "力", AltRune: "", Strokes: 2, Pinyin: "lì", Hiragana: "ちから", Romaji: "chikara", Meaning: "power, force", Freq: 163, Simplified: "", Examples: "力加助勉"},
	&Radical{Num: 20, Rune: "勹", AltRune: "", Strokes: 2, Pinyin: "bāo", Hiragana: "つつみがまえ", Romaji: "tsutsumigamae", Meaning: "wrap, embrace", Freq: 64, Simplified: "", Examples: "勾包"},
	&Radical{Num: 21, Rune: "匕", AltRune: "", Strokes: 2, Pinyin: "bǐ", Hiragana: "さじのひ", Romaji: "sajinohi", Meaning: "spoon", Freq: 19, Simplified: "", Examples: "化北"},
	&Radical{Num: 22, Rune: "匚", AltRune: "", Strokes: 2, Pinyin: "fāng", Hiragana: "はこがまえ", Romaji: "hakogamae", Meaning: "box", Freq: 64, Simplified: "", Examples: "匣"},
	&Radical{Num: 23, Rune: "匸", AltRune: "", Strokes: 2, Pinyin: "xǐ/xì", Hiragana: "かくしがまえ", Romaji: "kakushigamae", Meaning: "hiding enclosure", Freq: 17, Simplified: "", Examples: "匹區"},
	&Radical{Num: 24, Rune: "十", AltRune: "", Strokes: 2, Pinyin: "shí", Hiragana: "じゅう", Romaji: "jū", Meaning: "ten, complete", Freq: 55, Simplified: "", Examples: "十千午半博"},
	&Radical{Num: 25, Rune: "卜", AltRune: "", Strokes: 2, Pinyin: "bǔ", Hiragana: "ぼくのと", Romaji: "bokunoto", Meaning: "divination", Freq: 45, Simplified: "", Examples: "占卦"},
	&Radical{Num: 26, Rune: "卩", AltRune: "(㔾)", Strokes: 2, Pinyin: "jié", Hiragana: "ふしづくり", Romaji: "fushizukuri", Meaning: "seal", Freq: 40, Simplified: "", Examples: "印危卵"},
	&Radical{Num: 27, Rune: "厂", AltRune: "", Strokes: 2, Pinyin: "hàn", Hiragana: "がんだれ", Romaji: "gandare", Meaning: "cliff", Freq: 129, Simplified: "", Examples: "厚原"},
	&Radical{Num: 28, Rune: "厶", AltRune: "", Strokes: 2, Pinyin: "sī", Hiragana: "む", Romaji: "mu", Meaning: "private", Freq: 40, Simplified: "", Examples: "去參"},
	&Radical{Num: 29, Rune: "又", AltRune: "", Strokes: 2, Pinyin: "yòu", Hiragana: "また", Romaji: "mata", Meaning: "right hand", Freq: 91, Simplified: "", Examples: "友反取受"},
	&Radical{Num: 30, Rune: "口", AltRune: "", Strokes: 3, Pinyin: "kǒu", Hiragana: "くち", Romaji: "kuchi", Meaning: "mouth, opening", Freq: 1146, Simplified: "", Examples: "口古可名君否呉告周味命和哲唐善器"},
	&Radical{Num: 31, Rune: "囗", AltRune: "", Strokes: 3, Pinyin: "wéi", Hiragana: "くにがまえ", Romaji: "kunigamae", Meaning: "enclosure", Freq: 118, Simplified: "", Examples: "四回國圖"},
	&Radical{Num: 32, Rune: "土", AltRune: "", Strokes: 3, Pinyin: "tǔ", Hiragana: "つち", Romaji: "tsuchi", Meaning: "earth", Freq: 580, Simplified: "", Examples: "土在地型城場壁壓"},
	&Radical{Num: 33, Rune: "士", AltRune: "", Strokes: 3, Pinyin: "shì", Hiragana: "さむらい", Romaji: "samurai", Meaning: "scholar, bachelor", Freq: 24, Simplified: "", Examples: "士壹"},
	&Radical{Num: 34, Rune: "夂", AltRune: "", Strokes: 3, Pinyin: "zhǐ", Hiragana: "ふゆがしら", Romaji: "fuyugashira", Meaning: "go", Freq: 11, Simplified: "", Examples: "夆"},
	&Radical{Num: 35, Rune: "夊", AltRune: "", Strokes: 3, Pinyin: "suī", Hiragana: "すいにょう", Romaji: "suinyō", Meaning: "go slowly", Freq: 23, Simplified: "", Examples: "夏"},
	&Radical{Num: 36, Rune: "夕", AltRune: "", Strokes: 3, Pinyin: "xī", Hiragana: "ゆうべ", Romaji: "yūbe", Meaning: "evening, sunset", Freq: 34, Simplified: "", Examples: "夕外多夜"},
	&Radical{Num: 37, Rune: "大", AltRune: "", Strokes: 3, Pinyin: "dà", Hiragana: "だい", Romaji: "dai", Meaning: "big, very", Freq: 132, Simplified: "", Examples: "大天奈奧"},
	&Radical{Num: 38, Rune: "女", AltRune: "", Strokes: 3, Pinyin: "nǚ", Hiragana: "おんな", Romaji: "onna", Meaning: "woman, female", Freq: 681, Simplified: "", Examples: "女好妄妻姉始姓姫"},
	&Radical{Num: 39, Rune: "子", AltRune: "", Strokes: 3, Pinyin: "zǐ", Hiragana: "こ", Romaji: "ko", Meaning: "child, seed", Freq: 83, Simplified: "", Examples: "子孔字學"},
	&Radical{Num: 40, Rune: "宀", AltRune: "", Strokes: 3, Pinyin: "mián", Hiragana: "うかんむり", Romaji: "ukanmuri", Meaning: "roof", Freq: 246, Simplified: "", Examples: "守家寒實"},
	&Radical{Num: 41, Rune: "寸", AltRune: "", Strokes: 3, Pinyin: "cùn", Hiragana: "すん", Romaji: "sun", Meaning: "thumb, inch", Freq: 40, Simplified: "", Examples: "寸寺尊將"},
	&Radical{Num: 42, Rune: "小", AltRune: "(⺌, ⺍)", Strokes: 3, Pinyin: "xiǎo", Hiragana: "ちいさい", Romaji: "chīsai", Meaning: "small, insignificant", Freq: 41, Simplified: "", Examples: "小少"},
	&Radical{Num: 43, Rune: "尢", AltRune: "(尣)", Strokes: 3, Pinyin: "wāng", Hiragana: "まげあし", Romaji: "mageashi", Meaning: "lame", Freq: 66, Simplified: "", Examples: "就"},
	&Radical{Num: 44, Rune: "尸", AltRune: "", Strokes: 3, Pinyin: "shī", Hiragana: "しかばね", Romaji: "shikabane", Meaning: "corpse", Freq: 148, Simplified: "", Examples: "尺局"},
	&Radical{Num: 45, Rune: "屮", AltRune: "", Strokes: 3, Pinyin: "chè", Hiragana: "てつ", Romaji: "tetsu", Meaning: "sprout", Freq: 38, Simplified: "", Examples: "屯"},
	&Radical{Num: 46, Rune: "山", AltRune: "", Strokes: 3, Pinyin: "shān", Hiragana: "やま", Romaji: "yama", Meaning: "mountain", Freq: 636, Simplified: "", Examples: "山岡岩島"},
	&Radical{Num: 47, Rune: "巛", AltRune: "(川, 巜)", Strokes: 3, Pinyin: "chuān", Hiragana: "まがりがわ", Romaji: "magarigawa", Meaning: "river", Freq: 26, Simplified: "", Examples: "川州巡"},
	&Radical{Num: 48, Rune: "工", AltRune: "", Strokes: 3, Pinyin: "gōng", Hiragana: "たくみ", Romaji: "takumi", Meaning: "work", Freq: 17, Simplified: "", Examples: "工左巫差"},
	&Radical{Num: 49, Rune: "己", AltRune: "(巳, 已)", Strokes: 3, Pinyin: "jǐ", Hiragana: "おのれ", Romaji: "onore", Meaning: "oneself", Freq: 20, Simplified: "", Examples: "己巳"},
	&Radical{Num: 50, Rune: "巾", AltRune: "", Strokes: 3, Pinyin: "jīn", Hiragana: "はば", Romaji: "haba", Meaning: "turban, scarf", Freq: 295, Simplified: "", Examples: "市布帝常"},
	&Radical{Num: 51, Rune: "干", AltRune: "", Strokes: 3, Pinyin: "gān", Hiragana: "はす", Romaji: "hasu", Meaning: "dry", Freq: 9, Simplified: "", Examples: "平年"},
	&Radical{Num: 52, Rune: "幺", AltRune: "", Strokes: 3, Pinyin: "yāo", Hiragana: "いとがしら", Romaji: "itogashira", Meaning: "short, tiny", Freq: 50, Simplified: "", Examples: "幻幼"},
	&Radical{Num: 53, Rune: "广", AltRune: "", Strokes: 3, Pinyin: "yǎn", Hiragana: "まだれ", Romaji: "madare", Meaning: "house on cliff", Freq: 15, Simplified: "", Examples: "序店府度座庭廣廳"},
	&Radical{Num: 54, Rune: "廴", AltRune: "", Strokes: 3, Pinyin: "yín", Hiragana: "いんにょう", Romaji: "innyō", Meaning: "long stride", Freq: 9, Simplified: "", Examples: "延"},
	&Radical{Num: 55, Rune: "廾", AltRune: "", Strokes: 3, Pinyin: "gǒng", Hiragana: "にじゅうあし", Romaji: "nijyūashi", Meaning: "two hands, twenty", Freq: 50, Simplified: "", Examples: "弁"},
	&Radical{Num: 56, Rune: "弋", AltRune: "", Strokes: 3, Pinyin: "yì", Hiragana: "しきがまえ", Romaji: "shikigamae", Meaning: "shoot, arrow", Freq: 15, Simplified: "", Examples: "式弑"},
	&Radical{Num: 57, Rune: "弓", AltRune: "", Strokes: 3, Pinyin: "gōng", Hiragana: "ゆみ", Romaji: "yumi", Meaning: "bow", Freq: 165, Simplified: "", Examples: "弓引弟弱彌"},
	&Radical{Num: 58, Rune: "彐", AltRune: "(彑)", Strokes: 3, Pinyin: "jì", Hiragana: "けいがしら", Romaji: "keigashira", Meaning: "pig snout", Freq: 25, Simplified: "", Examples: "彖"},
	&Radical{Num: 59, Rune: "彡", AltRune: "", Strokes: 3, Pinyin: "shān", Hiragana: "さんづくり", Romaji: "sandzukuri", Meaning: "bristle, beard", Freq: 62, Simplified: "", Examples: "形彦"},
	&Radical{Num: 60, Rune: "彳", AltRune: "", Strokes: 3, Pinyin: "chì", Hiragana: "ぎょうにんべん", Romaji: "gyouninben", Meaning: "step", Freq: 215, Simplified: "", Examples: "役彼後得徳徼"},
	&Radical{Num: 61, Rune: "心", AltRune: "(忄,⺗)", Strokes: 4, Pinyin: "xīn", Hiragana: "りっしんべん", Romaji: "risshinben", Meaning: "heart", Freq: 1115, Simplified: "", Examples: "必忙忌性悪情想"},
	&Radical{Num: 62, Rune: "戈", AltRune: "", Strokes: 4, Pinyin: "gē", Hiragana: "かのほこ", Romaji: "kanohoko", Meaning: "spear, halberd", Freq: 116, Simplified: "", Examples: "成式弐戦"},
	&Radical{Num: 63, Rune: "戶", AltRune: "(户,戸)", Strokes: 4, Pinyin: "hù", Hiragana: "とびらのと", Romaji: "tobiranoto", Meaning: "door, house", Freq: 44, Simplified: "", Examples: "戸戻所"},
	&Radical{Num: 64, Rune: "手", AltRune: "(扌,龵)", Strokes: 4, Pinyin: "shǒu", Hiragana: "て", Romaji: "te", Meaning: "hand", Freq: 1203, Simplified: "", Examples: "手 才 持 掛 挙 拜 拳 掌 掣 擧 (打 批 技 抱 押)"},
	&Radical{Num: 65, Rune: "支", AltRune: "", Strokes: 4, Pinyin: "zhī", Hiragana: "しにょう", Romaji: "shinyō", Meaning: "branch", Freq: 26, Simplified: "", Examples: "攱攲"},
	&Radical{Num: 66, Rune: "攴", AltRune: "(攵)", Strokes: 4, Pinyin: "pū", Hiragana: "ぼくづくり", Romaji: "bokuzukuri", Meaning: "knock", Freq: 296, Simplified: "", Examples: "收敍數斅"},
	&Radical{Num: 67, Rune: "文", AltRune: "", Strokes: 4, Pinyin: "wén", Hiragana: "ぶんにょう", Romaji: "bunnnyō", Meaning: "script, literature", Freq: 26, Simplified: "", Examples: "文 斊 斈 斌 斐 斑 斕"},
	&Radical{Num: 68, Rune: "斗", AltRune: "", Strokes: 4, Pinyin: "dǒu", Hiragana: "とます", Romaji: "tomasu", Meaning: "dipper", Freq: 32, Simplified: "", Examples: "料 斡"},
	&Radical{Num: 69, Rune: "斤", AltRune: "", Strokes: 4, Pinyin: "jīn", Hiragana: "おの", Romaji: "ono", Meaning: "axe", Freq: 55, Simplified: "", Examples: "斦 斧 新 斥 斬 斷"},
	&Radical{Num: 70, Rune: "方", AltRune: "", Strokes: 4, Pinyin: "fāng", Hiragana: "ほう", Romaji: "hō", Meaning: "square, raft", Freq: 92, Simplified: "", Examples: "方 放 旅 族"},
	&Radical{Num: 71, Rune: "无", AltRune: "(旡)", Strokes: 4, Pinyin: "wú", Hiragana: "むにょう", Romaji: "mynyō", Meaning: "have not", Freq: 12, Simplified: "", Examples: "无 旡 既 旣"},
	&Radical{Num: 72, Rune: "日", AltRune: "", Strokes: 4, Pinyin: "rì", Hiragana: "にち", Romaji: "nichi", Meaning: "sun, day", Freq: 453, Simplified: "", Examples: "日白百明的映時晩"},
	&Radical{Num: 73, Rune: "曰", AltRune: "", Strokes: 4, Pinyin: "yuē", Hiragana: "いわく", Romaji: "iwaku", Meaning: "say", Freq: 37, Simplified: "", Examples: "書 最 晉 曷 曹 曾"},
	&Radical{Num: 74, Rune: "月", AltRune: "", Strokes: 4, Pinyin: "yuè", Hiragana: "つき", Romaji: "tsuki", Meaning: "moon, month", Freq: 69, Simplified: "", Examples: "有 服 青 朝"},
	&Radical{Num: 75, Rune: "木", AltRune: "", Strokes: 4, Pinyin: "mù", Hiragana: "き", Romaji: "ki", Meaning: "tree", Freq: 1369, Simplified: "", Examples: "木 杢 板 相 根 森 楽 機 末 本 杉 林"},
	&Radical{Num: 76, Rune: "欠", AltRune: "", Strokes: 4, Pinyin: "qiàn", Hiragana: "あくび", Romaji: "akubi", Meaning: "yawn", Freq: 235, Simplified: "", Examples: "欣 欽 欧 欲 歌"},
	&Radical{Num: 77, Rune: "止", AltRune: "", Strokes: 4, Pinyin: "zhǐ", Hiragana: "とめる", Romaji: "tomeru", Meaning: "stop", Freq: 99, Simplified: "", Examples: "正 歩 此 步 武 歪 歲"},
	&Radical{Num: 78, Rune: "歹", AltRune: "(歺)", Strokes: 4, Pinyin: "dǎi", Hiragana: "がつへん", Romaji: "gatsuhen", Meaning: "death, decay", Freq: 231, Simplified: "", Examples: "死 列 殕"},
	&Radical{Num: 79, Rune: "殳", AltRune: "", Strokes: 4, Pinyin: "shū", Hiragana: "ほこつくり", Romaji: "hokotsukuri", Meaning: "weapon, lance", Freq: 93, Simplified: "", Examples: "役 投 殴 殷"},
	&Radical{Num: 80, Rune: "毋", AltRune: "(母, ⺟)", Strokes: 4, Pinyin: "wú", Hiragana: "なかれ", Romaji: "nakare", Meaning: "do not", Freq: 16, Simplified: "", Examples: "毋 母 毎 姆 梅"},
	&Radical{Num: 81, Rune: "比", AltRune: "", Strokes: 4, Pinyin: "bǐ", Hiragana: "くらべる", Romaji: "kuraberu", Meaning: "compare, compete", Freq: 21, Simplified: "", Examples: "皆 批 毕 毖 毘 毚"},
	&Radical{Num: 82, Rune: "毛", AltRune: "", Strokes: 4, Pinyin: "máo", Hiragana: "け", Romaji: "ke", Meaning: "fur, hair", Freq: 211, Simplified: "", Examples: "毟 毡 毦 毫 毳 耗"},
	&Radical{Num: 83, Rune: "氏", AltRune: "", Strokes: 4, Pinyin: "shì", Hiragana: "うじ", Romaji: "uji", Meaning: "clan", Freq: 10, Simplified: "", Examples: "氏 民 紙 婚 氓"},
	&Radical{Num: 84, Rune: "气", AltRune: "", Strokes: 4, Pinyin: "qì", Hiragana: "きがまえ", Romaji: "kigamae", Meaning: "steam, breath", Freq: 17, Simplified: "", Examples: "気 汽 氧"},
	&Radical{Num: 85, Rune: "水", AltRune: "(氵,氺)", Strokes: 4, Pinyin: "shuǐ", Hiragana: "みず", Romaji: "mizu", Meaning: "water", Freq: 1595, Simplified: "", Examples: "水 永 泳 決 治 海 演 漢 瀬"},
	&Radical{Num: 86, Rune: "火", AltRune: "(灬)", Strokes: 4, Pinyin: "huǒ", Hiragana: "ひ", Romaji: "hi", Meaning: "fire", Freq: 639, Simplified: "", Examples: "火 灯 毯 爆 (烈 烹 焦 然 煮)"},
	&Radical{Num: 87, Rune: "爪", AltRune: "(爫)", Strokes: 4, Pinyin: "zhǎo", Hiragana: "つめ", Romaji: "tsume", Meaning: "claw, nail, talon", Freq: 36, Simplified: "", Examples: "爬 爯 爭 爰 爲"},
	&Radical{Num: 88, Rune: "父", AltRune: "", Strokes: 4, Pinyin: "fù", Hiragana: "ちち", Romaji: "chichi", Meaning: "father", Freq: 10, Simplified: "", Examples: "斧 釜"},
	&Radical{Num: 89, Rune: "爻", AltRune: "", Strokes: 4, Pinyin: "yáo", Hiragana: "コウ", Romaji: "kō", Meaning: "mix, twine, cross", Freq: 16, Simplified: "", Examples: "爼 爽 爾"},
	&Radical{Num: 90, Rune: "爿", AltRune: "(丬)", Strokes: 4, Pinyin: "qiáng", Hiragana: "しょうへん", Romaji: "shyōhen", Meaning: "split wood", Freq: 48, Simplified: "", Examples: "牀 奘 牃"},
	&Radical{Num: 91, Rune: "片", AltRune: "", Strokes: 4, Pinyin: "piàn", Hiragana: "かた", Romaji: "kata", Meaning: "slice", Freq: 77, Simplified: "", Examples: "版 牌 牒"},
	&Radical{Num: 92, Rune: "牙", AltRune: "", Strokes: 4, Pinyin: "yá", Hiragana: "きばへん", Romaji: "kibahen", Meaning: "fang", Freq: 9, Simplified: "", Examples: "芽 呀 牚"},
	&Radical{Num: 93, Rune: "牛", AltRune: "(牜, ⺧)", Strokes: 4, Pinyin: "niú", Hiragana: "うし", Romaji: "ushi", Meaning: "cow", Freq: 233, Simplified: "", Examples: "告 牟 牧 物 特 解"},
	&Radical{Num: 94, Rune: "犬", AltRune: "(犭)", Strokes: 4, Pinyin: "quǎn", Hiragana: "いぬ", Romaji: "inu", Meaning: "dog", Freq: 444, Simplified: "", Examples: "犬 犯 狂 狙 狗 献 獣"},
	&Radical{Num: 95, Rune: "玄", AltRune: "", Strokes: 5, Pinyin: "xuán", Hiragana: "げん", Romaji: "gen", Meaning: "dark, profound", Freq: 6, Simplified: "", Examples: "弦玆"},
	&Radical{Num: 96, Rune: "玉", AltRune: "(玊, 王, ⺩)", Strokes: 5, Pinyin: "yù", Hiragana: "たま", Romaji: "tama", Meaning: "jade", Freq: 473, Simplified: "", Examples: "王 玉 主 弄 皇 理 差 聖"},
	&Radical{Num: 97, Rune: "瓜", AltRune: "", Strokes: 5, Pinyin: "guā", Hiragana: "うり", Romaji: "uri", Meaning: "melon", Freq: 55, Simplified: "", Examples: "呱 瓞"},
	&Radical{Num: 98, Rune: "瓦", AltRune: "", Strokes: 5, Pinyin: "wǎ", Hiragana: "かわら", Romaji: "kawara", Meaning: "tile", Freq: 174, Simplified: "", Examples: "瓧 瓮 甄"},
	&Radical{Num: 99, Rune: "甘", AltRune: "", Strokes: 5, Pinyin: "gān", Hiragana: "あまい", Romaji: "amai", Meaning: "sweet", Freq: 22, Simplified: "", Examples: "柑 甜 酣"},
	&Radical{Num: 100, Rune: "生", AltRune: "", Strokes: 5, Pinyin: "shēng", Hiragana: "うまれる", Romaji: "umareru", Meaning: "life", Freq: 22, Simplified: "", Examples: "牲 笙 甥"},
	&Radical{Num: 101, Rune: "用", AltRune: "(甩)", Strokes: 5, Pinyin: "yòng (shuǎi)", Hiragana: "もちいる", Romaji: "mochīru", Meaning: "use, throw", Freq: 10, Simplified: "", Examples: "佣 甬 甯"},
	&Radical{Num: 102, Rune: "田", AltRune: "", Strokes: 5, Pinyin: "tián", Hiragana: "た", Romaji: "ta", Meaning: "field", Freq: 192, Simplified: "", Examples: "田 町 思 留 略 番"},
	&Radical{Num: 103, Rune: "疋", AltRune: "(⺪)", Strokes: 5, Pinyin: "pǐ", Hiragana: "ひき", Romaji: "hiki", Meaning: "bolt of cloth", Freq: 15, Simplified: "", Examples: "疏 楚 胥 延"},
	&Radical{Num: 104, Rune: "疒", AltRune: "", Strokes: 5, Pinyin: "nè", Hiragana: "やまいだれ", Romaji: "yamaidare", Meaning: "sickness", Freq: 526, Simplified: "", Examples: "病 症 痛 癌 癖"},
	&Radical{Num: 105, Rune: "癶", AltRune: "", Strokes: 5, Pinyin: "bō", Hiragana: "はつがしら", Romaji: "hatsugashira", Meaning: "footsteps", Freq: 15, Simplified: "", Examples: "発 登"},
	&Radical{Num: 106, Rune: "白", AltRune: "", Strokes: 5, Pinyin: "bái", Hiragana: "しろ", Romaji: "shiro", Meaning: "white", Freq: 109, Simplified: "", Examples: "皃 的 皆 皇"},
	&Radical{Num: 107, Rune: "皮", AltRune: "", Strokes: 5, Pinyin: "pí", Hiragana: "けがわ", Romaji: "kegawa", Meaning: "skin", Freq: 94, Simplified: "", Examples: "披 彼 波"},
	&Radical{Num: 108, Rune: "皿", AltRune: "", Strokes: 5, Pinyin: "mǐn", Hiragana: "さら", Romaji: "sara", Meaning: "dish", Freq: 129, Simplified: "", Examples: "盂 盉 盍 監 蘯"},
	&Radical{Num: 109, Rune: "目", AltRune: "", Strokes: 5, Pinyin: "mù", Hiragana: "め", Romaji: "me", Meaning: "eye", Freq: 647, Simplified: "", Examples: "目 見 具 省 眠 眼 観 覧"},
	&Radical{Num: 110, Rune: "矛", AltRune: "", Strokes: 5, Pinyin: "máo", Hiragana: "むのほこ", Romaji: "munohoko", Meaning: "spear", Freq: 65, Simplified: "", Examples: "茅 矜"},
	&Radical{Num: 111, Rune: "矢", AltRune: "", Strokes: 5, Pinyin: "shǐ", Hiragana: "や", Romaji: "ya", Meaning: "arrow", Freq: 64, Simplified: "", Examples: "医 族 矩"},
	&Radical{Num: 112, Rune: "石", AltRune: "", Strokes: 5, Pinyin: "shí", Hiragana: "いし", Romaji: "ishi", Meaning: "stone", Freq: 499, Simplified: "", Examples: "石 岩 砂 破 碑 碧"},
	&Radical{Num: 113, Rune: "示", AltRune: "(礻)", Strokes: 5, Pinyin: "shì", Hiragana: "しめす", Romaji: "shimesu", Meaning: "sign", Freq: 213, Simplified: "", Examples: "示 礼 社 奈 神 祭 視 禁 福"},
	&Radical{Num: 114, Rune: "禸", AltRune: "", Strokes: 5, Pinyin: "róu", Hiragana: "ぐうのあし", Romaji: "gūnoashi", Meaning: "track", Freq: 12, Simplified: "", Examples: "禹 禺 禽"},
	&Radical{Num: 115, Rune: "禾", AltRune: "", Strokes: 5, Pinyin: "hé", Hiragana: "のぎ", Romaji: "nogi", Meaning: "grain", Freq: 431, Simplified: "", Examples: "利 私 季 和 科 香 秦 穀"},
	&Radical{Num: 116, Rune: "穴", AltRune: "", Strokes: 5, Pinyin: "xué", Hiragana: "あな", Romaji: "ana", Meaning: "cave", Freq: 298, Simplified: "", Examples: "空 突 窅 窘 窩 窶 竇"},
	&Radical{Num: 117, Rune: "立", AltRune: "", Strokes: 5, Pinyin: "lì", Hiragana: "たつ", Romaji: "tatsu", Meaning: "stand, erect", Freq: 101, Simplified: "", Examples: "立 音 産 翌 意 新 端 親 競"},
	&Radical{Num: 118, Rune: "竹", AltRune: "(⺮)", Strokes: 6, Pinyin: "zhú", Hiragana: "たけ", Romaji: "take", Meaning: "bamboo", Freq: 953, Simplified: "", Examples: "竺 笑 第 等 簡"},
	&Radical{Num: 119, Rune: "米", AltRune: "", Strokes: 6, Pinyin: "mǐ", Hiragana: "こめ", Romaji: "kome", Meaning: "rice", Freq: 318, Simplified: "", Examples: "料 断 奥 糊 麟"},
	&Radical{Num: 120, Rune: "糸", AltRune: "(糹)", Strokes: 6, Pinyin: "mì", Hiragana: "いと", Romaji: "ito", Meaning: "silk", Freq: 823, Simplified: "纟", Examples: "系 級 紙 素 細 組 終 絵 紫"},
	&Radical{Num: 121, Rune: "缶", AltRune: "", Strokes: 6, Pinyin: "fǒu", Hiragana: "ほとぎ", Romaji: "hotogi", Meaning: "jar", Freq: 77, Simplified: "", Examples: "缶 缸 窑 陶"},
	&Radical{Num: 122, Rune: "网", AltRune: "(罒,⺲,罓,⺳)", Strokes: 6, Pinyin: "wǎng", Hiragana: "あみがしら", Romaji: "amigashira", Meaning: "net", Freq: 163, Simplified: "", Examples: "買 罪 置 羅"},
	&Radical{Num: 123, Rune: "羊", AltRune: "(⺶,⺷)", Strokes: 6, Pinyin: "yáng", Hiragana: "ひつじ", Romaji: "hitsuji", Meaning: "sheep", Freq: 156, Simplified: "", Examples: "着 羚 翔 着"},
	&Radical{Num: 124, Rune: "羽", AltRune: "", Strokes: 6, Pinyin: "yǔ", Hiragana: "はね", Romaji: "hane", Meaning: "feather", Freq: 220, Simplified: "", Examples: "習 翀 翁 翔"},
	&Radical{Num: 125, Rune: "老", AltRune: "(耂)", Strokes: 6, Pinyin: "lǎo", Hiragana: "おい", Romaji: "oi", Meaning: "old", Freq: 22, Simplified: "", Examples: "耆孝耋"},
	&Radical{Num: 126, Rune: "而", AltRune: "", Strokes: 6, Pinyin: "ér", Hiragana: "しかして", Romaji: "shikashite", Meaning: "beard", Freq: 22, Simplified: "", Examples: "耎耐耑"},
	&Radical{Num: 127, Rune: "耒", AltRune: "", Strokes: 6, Pinyin: "lěi", Hiragana: "らいすき", Romaji: "raisuki", Meaning: "plow", Freq: 84, Simplified: "", Examples: "耔 耝 耨 耰"},
	&Radical{Num: 128, Rune: "耳", AltRune: "", Strokes: 6, Pinyin: "ěr", Hiragana: "みみ", Romaji: "mimi", Meaning: "ear", Freq: 172, Simplified: "", Examples: "取 聞 職 叢"},
	&Radical{Num: 129, Rune: "聿", AltRune: "(⺻)", Strokes: 6, Pinyin: "yù", Hiragana: "ふでづくり", Romaji: "fudezukuri", Meaning: "brush", Freq: 19, Simplified: "", Examples: "律 書 建"},
	&Radical{Num: 130, Rune: "肉", AltRune: "(⺼)", Strokes: 6, Pinyin: "ròu", Hiragana: "にく", Romaji: "niku", Meaning: "meat", Freq: 674, Simplified: "", Examples: "肉 肖 股 胃 腅 脤"},
	&Radical{Num: 131, Rune: "臣", AltRune: "", Strokes: 6, Pinyin: "chén", Hiragana: "しん", Romaji: "shin", Meaning: "minister, official", Freq: 16, Simplified: "", Examples: "臥 宦 蔵"},
	&Radical{Num: 132, Rune: "自", AltRune: "", Strokes: 6, Pinyin: "zì", Hiragana: "みずから", Romaji: "mizukara", Meaning: "self", Freq: 34, Simplified: "", Examples: "自 臫 臬 臲"},
	&Radical{Num: 133, Rune: "至", AltRune: "", Strokes: 6, Pinyin: "zhì", Hiragana: "いたる", Romaji: "itaru", Meaning: "arrive", Freq: 24, Simplified: "", Examples: "致 臸 臺"},
	&Radical{Num: 134, Rune: "臼", AltRune: "", Strokes: 6, Pinyin: "jiù", Hiragana: "うす", Romaji: "usu", Meaning: "mortar", Freq: 71, Simplified: "", Examples: "桕 舅 舂 鼠 插"},
	&Radical{Num: 135, Rune: "舌", AltRune: "", Strokes: 6, Pinyin: "shé", Hiragana: "した", Romaji: "shita", Meaning: "tongue", Freq: 31, Simplified: "", Examples: "乱 适 話 舍"},
	&Radical{Num: 136, Rune: "舛", AltRune: "", Strokes: 6, Pinyin: "chuǎn", Hiragana: "ます", Romaji: "masu", Meaning: "opposite", Freq: 10, Simplified: "", Examples: "舛 舜 舞"},
	&Radical{Num: 137, Rune: "舟", AltRune: "", Strokes: 6, Pinyin: "zhōu", Hiragana: "ふね", Romaji: "fune", Meaning: "boat", Freq: 197, Simplified: "", Examples: "航 船 艦"},
	&Radical{Num: 138, Rune: "艮", AltRune: "", Strokes: 6, Pinyin: "gēn", Hiragana: "うしとら", Romaji: "ushitora", Meaning: "stopping", Freq: 5, Simplified: "", Examples: "良 飲 很"},
	&Radical{Num: 139, Rune: "色", AltRune: "", Strokes: 6, Pinyin: "sè", Hiragana: "いろ", Romaji: "iro", Meaning: "colour, prettiness", Freq: 21, Simplified: "", Examples: "色 艴 艷"},
	&Radical{Num: 140, Rune: "艸", AltRune: "(艹)", Strokes: 6, Pinyin: "cǎo", Hiragana: "くさ", Romaji: "kusa", Meaning: "grass", Freq: 1902, Simplified: "", Examples: "共 花 英 苦 草 茶 落 幕 靴 鞄 薬"},
	&Radical{Num: 141, Rune: "虍", AltRune: "", Strokes: 6, Pinyin: "hū", Hiragana: "とらかんむり", Romaji: "torakanmuri", Meaning: "tiger stripes", Freq: 114, Simplified: "", Examples: "虎 虐 彪 虒"},
	&Radical{Num: 142, Rune: "虫", AltRune: "", Strokes: 6, Pinyin: "huǐ", Hiragana: "むし", Romaji: "mushi", Meaning: "insect", Freq: 1067, Simplified: "(pr. chóng)", Examples: "蚯 蚓 強 触 蟻 蟹"},
	&Radical{Num: 143, Rune: "血", AltRune: "", Strokes: 6, Pinyin: "xuè", Hiragana: "ち", Romaji: "chi", Meaning: "blood", Freq: 60, Simplified: "", Examples: "洫 衁 衅 衆"},
	&Radical{Num: 144, Rune: "行", AltRune: "", Strokes: 6, Pinyin: "xíng", Hiragana: "ぎょう", Romaji: "gyō", Meaning: "go, do", Freq: 53, Simplified: "", Examples: "行 衍 術 衝"},
	&Radical{Num: 145, Rune: "衣", AltRune: "(衤)", Strokes: 6, Pinyin: "yī", Hiragana: "ころも", Romaji: "koromo", Meaning: "clothes", Freq: 607, Simplified: "", Examples: "衣 初 被 装 裁 複"},
	&Radical{Num: 146, Rune: "西", AltRune: "(襾,覀)", Strokes: 6, Pinyin: "xī", Hiragana: "にし", Romaji: "nishi", Meaning: "west", Freq: 29, Simplified: "", Examples: "西 要 覊"},
	&Radical{Num: 147, Rune: "見", AltRune: "", Strokes: 7, Pinyin: "jiàn", Hiragana: "みる", Romaji: "miru", Meaning: "see", Freq: 161, Simplified: "见", Examples: "規 親 覺 觀"},
	&Radical{Num: 148, Rune: "角", AltRune: "", Strokes: 7, Pinyin: "jiǎo", Hiragana: "つの", Romaji: "tsuno", Meaning: "horn", Freq: 158, Simplified: "", Examples: "觚 解 觕 觥 觸"},
	&Radical{Num: 149, Rune: "言", AltRune: "(訁)", Strokes: 7, Pinyin: "yán", Hiragana: "ことば", Romaji: "kotoba", Meaning: "speech", Freq: 861, Simplified: "讠", Examples: "誁 詋 詔 評 詗 詥 試 詧"},
	&Radical{Num: 150, Rune: "谷", AltRune: "", Strokes: 7, Pinyin: "gǔ", Hiragana: "たに", Romaji: "tani", Meaning: "valley", Freq: 54, Simplified: "", Examples: "谿 豀 谸"},
	&Radical{Num: 151, Rune: "豆", AltRune: "", Strokes: 7, Pinyin: "dòu", Hiragana: "まめ", Romaji: "mame", Meaning: "bean", Freq: 68, Simplified: "", Examples: "豈 豐 豎"},
	&Radical{Num: 152, Rune: "豕", AltRune: "", Strokes: 7, Pinyin: "shǐ", Hiragana: "いのこ", Romaji: "inoko", Meaning: "pig", Freq: 148, Simplified: "", Examples: "豖 豚 象"},
	&Radical{Num: 153, Rune: "豸", AltRune: "", Strokes: 7, Pinyin: "zhì", Hiragana: "むじな", Romaji: "mujina", Meaning: "cat, badger", Freq: 140, Simplified: "", Examples: "豹 貌 貓 貈 貉"},
	&Radical{Num: 154, Rune: "貝", AltRune: "", Strokes: 7, Pinyin: "bèi", Hiragana: "かい", Romaji: "kai", Meaning: "shell", Freq: 277, Simplified: "贝", Examples: "財 賊 賜 贛 貧 貨 貫 貿"},
	&Radical{Num: 155, Rune: "赤", AltRune: "", Strokes: 7, Pinyin: "chì", Hiragana: "あか", Romaji: "aka", Meaning: "red, bare", Freq: 31, Simplified: "", Examples: "赫 赭"},
	&Radical{Num: 156, Rune: "走", AltRune: "(赱)", Strokes: 7, Pinyin: "zǒu", Hiragana: "はしる", Romaji: "hashiru", Meaning: "run", Freq: 285, Simplified: "", Examples: "赴 起 超"},
	&Radical{Num: 157, Rune: "足", AltRune: "(⻊)", Strokes: 7, Pinyin: "zú", Hiragana: "あし", Romaji: "ashi", Meaning: "foot", Freq: 580, Simplified: "", Examples: "跑 跨 跟 跪 路"},
	&Radical{Num: 158, Rune: "身", AltRune: "", Strokes: 7, Pinyin: "shēn", Hiragana: "み", Romaji: "mi", Meaning: "body", Freq: 97, Simplified: "", Examples: "躬 躲 軀"},
	&Radical{Num: 159, Rune: "車", AltRune: "", Strokes: 7, Pinyin: "chē", Hiragana: "くるま", Romaji: "kuruma", Meaning: "cart, car", Freq: 361, Simplified: "车", Examples: "軌 軟 較 軍 載"},
	&Radical{Num: 160, Rune: "辛", AltRune: "", Strokes: 7, Pinyin: "xīn", Hiragana: "からい", Romaji: "karai", Meaning: "bitter", Freq: 36, Simplified: "", Examples: "辜 辟 辣 辦 辨"},
	&Radical{Num: 161, Rune: "辰", AltRune: "", Strokes: 7, Pinyin: "chén", Hiragana: "しんのたつ", Romaji: "shinnotatsu", Meaning: "morning", Freq: 15, Simplified: "", Examples: "辱 農"},
	&Radical{Num: 162, Rune: "辵", AltRune: "(辶,⻌,⻍)", Strokes: 7, Pinyin: "chuò / zouzhi", Hiragana: "しんにゅう", Romaji: "shinnyū", Meaning: "walk", Freq: 381, Simplified: "", Examples: "巡 迎 通 追 逃 辶 迎 進"},
	&Radical{Num: 163, Rune: "邑", AltRune: "(", Strokes: 7, Pinyin: "yì", Hiragana: "むら", Romaji: "mura", Meaning: "town", Freq: 350, Simplified: "", Examples: "那 邦 郎 部 郭 都 鄉"},
	&Radical{Num: 164, Rune: "酉", AltRune: "", Strokes: 7, Pinyin: "yǒu", Hiragana: "ひよみのとり", Romaji: "hyominotori", Meaning: "wine, alcohol", Freq: 290, Simplified: "", Examples: "醉 酱 油 醒 酸"},
	&Radical{Num: 165, Rune: "釆", AltRune: "", Strokes: 7, Pinyin: "biàn", Hiragana: "のごめ", Romaji: "nogome", Meaning: "divide, distinguish, choose", Freq: 14, Simplified: "", Examples: "釉 釋"},
	&Radical{Num: 166, Rune: "里", AltRune: "", Strokes: 7, Pinyin: "lǐ", Hiragana: "さと", Romaji: "sato", Meaning: "village, mile", Freq: 14, Simplified: "", Examples: "野 野"},
	&Radical{Num: 167, Rune: "金", AltRune: "(釒)", Strokes: 8, Pinyin: "jīn", Hiragana: "かね", Romaji: "kane", Meaning: "metal, gold", Freq: 806, Simplified: "钅", Examples: "銀 銅 釘 銳 鋞 鋙 鉒 鉍 鉗 鈡 鈠"},
	&Radical{Num: 168, Rune: "長", AltRune: "(镸)", Strokes: 8, Pinyin: "cháng", Hiragana: "ながい", Romaji: "nagai", Meaning: "long, grow", Freq: 55, Simplified: "长", Examples: "镸 镽"},
	&Radical{Num: 169, Rune: "門", AltRune: "", Strokes: 8, Pinyin: "mén", Hiragana: "もん", Romaji: "mon", Meaning: "gate", Freq: 246, Simplified: "门", Examples: "間 閑 關 闘 閉 開 閏 間 關"},
	&Radical{Num: 170, Rune: "阜", AltRune: "(阝)", Strokes: 8, Pinyin: "fù", Hiragana: "ぎふのふ", Romaji: "gifunofu", Meaning: "mound, dam", Freq: 348, Simplified: "", Examples: "阪 防 阻 陆 陘 院 险 陳"},
	&Radical{Num: 171, Rune: "隶", AltRune: "", Strokes: 8, Pinyin: "lì", Hiragana: "れいづくり", Romaji: "reizukuri", Meaning: "slave, capture", Freq: 12, Simplified: "", Examples: "隸 隺"},
	&Radical{Num: 172, Rune: "隹", AltRune: "", Strokes: 8, Pinyin: "zhuī", Hiragana: "ふるとり", Romaji: "furutori", Meaning: "small bird", Freq: 233, Simplified: "", Examples: "雀 集 雁 难 雀 雅"},
	&Radical{Num: 173, Rune: "雨", AltRune: "", Strokes: 8, Pinyin: "yǔ", Hiragana: "あめ", Romaji: "ame", Meaning: "rain", Freq: 298, Simplified: "", Examples: "雾 霜 雪 霸 雲 霧"},
	&Radical{Num: 174, Rune: "青", AltRune: "(靑)", Strokes: 8, Pinyin: "qīng", Hiragana: "あお", Romaji: "ao", Meaning: "green, blue", Freq: 17, Simplified: "", Examples: "靕 靖 靜"},
	&Radical{Num: 175, Rune: "非", AltRune: "", Strokes: 8, Pinyin: "fēi", Hiragana: "あらず", Romaji: "arazu", Meaning: "wrong", Freq: 25, Simplified: "", Examples: "靠 靠 靟"},
	&Radical{Num: 176, Rune: "面", AltRune: "(靣)", Strokes: 9, Pinyin: "miàn", Hiragana: "めん", Romaji: "men", Meaning: "face", Freq: 66, Simplified: "", Examples: "靦 靨"},
	&Radical{Num: 177, Rune: "革", AltRune: "", Strokes: 9, Pinyin: "gé", Hiragana: "かくのかわ", Romaji: "kakunokawa", Meaning: "leather, rawhide", Freq: 305, Simplified: "", Examples: "靴 鞍 鞅 鞍 鞭"},
	&Radical{Num: 178, Rune: "韋", AltRune: "", Strokes: 9, Pinyin: "wéi", Hiragana: "なめしがわ", Romaji: "nameshigawa", Meaning: "tanned leather", Freq: 100, Simplified: "韦", Examples: "韋 韓 韜"},
	&Radical{Num: 179, Rune: "韭", AltRune: "", Strokes: 9, Pinyin: "jiǔ", Hiragana: "にら", Romaji: "nira", Meaning: "leek", Freq: 20, Simplified: "", Examples: "韱 韲"},
	&Radical{Num: 180, Rune: "音", AltRune: "", Strokes: 9, Pinyin: "yīn", Hiragana: "おと", Romaji: "oto", Meaning: "sound", Freq: 43, Simplified: "", Examples: "韶 韻 韾"},
	&Radical{Num: 181, Rune: "頁", AltRune: "", Strokes: 9, Pinyin: "yè", Hiragana: "おおがい", Romaji: "ōgai", Meaning: "leaf", Freq: 372, Simplified: "页", Examples: "頃 項 順 須 領 頭 頩 頂"},
	&Radical{Num: 182, Rune: "風", AltRune: "", Strokes: 9, Pinyin: "fēng", Hiragana: "かぜ", Romaji: "kaze", Meaning: "wind", Freq: 182, Simplified: "风", Examples: "颱 飄 颿 颩 颪"},
	&Radical{Num: 183, Rune: "飛", AltRune: "", Strokes: 9, Pinyin: "fēi", Hiragana: "とぶ", Romaji: "tobu", Meaning: "fly", Freq: 92, Simplified: "飞", Examples: "飜 飝"},
	&Radical{Num: 184, Rune: "食", AltRune: "(飠)", Strokes: 9, Pinyin: "shí", Hiragana: "しょく", Romaji: "shyoku", Meaning: "eat, food", Freq: 403, Simplified: "饣", Examples: "飯 飲 餓 餘 餐 養"},
	&Radical{Num: 185, Rune: "首", AltRune: "", Strokes: 9, Pinyin: "shǒu", Hiragana: "くび", Romaji: "kubi", Meaning: "head", Freq: 20, Simplified: "", Examples: "馗 馘"},
	&Radical{Num: 186, Rune: "香", AltRune: "", Strokes: 9, Pinyin: "xiāng", Hiragana: "においこう", Romaji: "nioikō", Meaning: "fragrant", Freq: 37, Simplified: "", Examples: "馨 馫"},
	&Radical{Num: 187, Rune: "馬", AltRune: "", Strokes: 10, Pinyin: "mǎ", Hiragana: "うま", Romaji: "uma", Meaning: "horse", Freq: 472, Simplified: "马", Examples: "馮 馴 馳 駐 驚"},
	&Radical{Num: 188, Rune: "骨", AltRune: "", Strokes: 10, Pinyin: "gǔ", Hiragana: "ほね", Romaji: "hone", Meaning: "bone", Freq: 185, Simplified: "", Examples: "骼 髒 髀 骿 骾"},
	&Radical{Num: 189, Rune: "高", AltRune: "(髙)", Strokes: 10, Pinyin: "gāo", Hiragana: "たかい", Romaji: "takai", Meaning: "tall, high", Freq: 34, Simplified: "", Examples: "髚 髛"},
	&Radical{Num: 190, Rune: "髟", AltRune: "", Strokes: 10, Pinyin: "biāo", Hiragana: "かみがしら", Romaji: "kamigashira", Meaning: "hair", Freq: 243, Simplified: "", Examples: "髮 鬚 鬆 鬍 髦"},
	&Radical{Num: 191, Rune: "鬥", AltRune: "", Strokes: 10, Pinyin: "dòu", Hiragana: "とうがまえ", Romaji: "tōgamae", Meaning: "fight", Freq: 23, Simplified: "", Examples: "鬧 鬪"},
	&Radical{Num: 192, Rune: "鬯", AltRune: "", Strokes: 10, Pinyin: "chàng", Hiragana: "ちょう", Romaji: "chyō", Meaning: "herbs, sacrificial wine", Freq: 8, Simplified: "", Examples: "鬰 鬱"},
	&Radical{Num: 193, Rune: "鬲", AltRune: "", Strokes: 10, Pinyin: "lì", Hiragana: "かなえ", Romaji: "kanae", Meaning: "tripod, cauldron", Freq: 73, Simplified: "", Examples: "鬶 鬷 鬸"},
	&Radical{Num: 194, Rune: "鬼", AltRune: "", Strokes: 10, Pinyin: "guǐ", Hiragana: "おに", Romaji: "oni", Meaning: "ghost, demon", Freq: 141, Simplified: "", Examples: "魂 魁 鬽 魄"},
	&Radical{Num: 195, Rune: "魚", AltRune: "", Strokes: 11, Pinyin: "yú", Hiragana: "うお", Romaji: "uo", Meaning: "fish", Freq: 571, Simplified: "鱼", Examples: "鯉 鮑 魛 魜 魝 魞 魟 魠"},
	&Radical{Num: 196, Rune: "鳥", AltRune: "", Strokes: 11, Pinyin: "niǎo", Hiragana: "とり", Romaji: "tori", Meaning: "bird", Freq: 750, Simplified: "鸟", Examples: "鳫 鳮 鳱 鳳 鳴 鳿 雞 鳴 鴻 鴛"},
	&Radical{Num: 197, Rune: "鹵", AltRune: "", Strokes: 11, Pinyin: "lǔ", Hiragana: "ろ", Romaji: "ro", Meaning: "salt", Freq: 44, Simplified: "卤", Examples: "鹹 鹼 鹽"},
	&Radical{Num: 198, Rune: "鹿", AltRune: "", Strokes: 11, Pinyin: "lù", Hiragana: "しか", Romaji: "shika", Meaning: "deer", Freq: 104, Simplified: "", Examples: "塵 麃 麋 麉 麟"},
	&Radical{Num: 199, Rune: "麥", AltRune: "", Strokes: 11, Pinyin: "mài", Hiragana: "むぎ", Romaji: "mugi", Meaning: "wheat", Freq: 131, Simplified: "麦", Examples: "麴 麵 麱 麨 麺"},
	&Radical{Num: 200, Rune: "麻", AltRune: "", Strokes: 11, Pinyin: "má", Hiragana: "あさ", Romaji: "asa", Meaning: "hemp, flax", Freq: 34, Simplified: "", Examples: "麼 魔"},
	&Radical{Num: 201, Rune: "黃", AltRune: "", Strokes: 12, Pinyin: "huáng", Hiragana: "きいろ", Romaji: "kīru", Meaning: "yellow", Freq: 42, Simplified: "", Examples: "黊 黌"},
	&Radical{Num: 202, Rune: "黍", AltRune: "", Strokes: 12, Pinyin: "shǔ", Hiragana: "きび", Romaji: "kibi", Meaning: "millet", Freq: 46, Simplified: "", Examples: "黏 黎"},
	&Radical{Num: 203, Rune: "黑", AltRune: "", Strokes: 12, Pinyin: "hēi", Hiragana: "くろ", Romaji: "kuro", Meaning: "black", Freq: 172, Simplified: "", Examples: "點 黛 黱 黨"},
	&Radical{Num: 204, Rune: "黹", AltRune: "", Strokes: 12, Pinyin: "zhǐ", Hiragana: "ふつ", Romaji: "futsu", Meaning: "embroidery, needlework", Freq: 8, Simplified: "", Examples: "黼 黻"},
	&Radical{Num: 205, Rune: "黽", AltRune: "", Strokes: 13, Pinyin: "mǐn", Hiragana: "べん", Romaji: "ben", Meaning: "frog, amphibian", Freq: 40, Simplified: "黾", Examples: "鼈 黿 鼆"},
	&Radical{Num: 206, Rune: "鼎", AltRune: "", Strokes: 13, Pinyin: "dǐng", Hiragana: "かなえ", Romaji: "kanae", Meaning: "sacrificial tripod", Freq: 14, Simplified: "", Examples: "鼏 鼒"},
	&Radical{Num: 207, Rune: "鼓", AltRune: "", Strokes: 13, Pinyin: "gǔ", Hiragana: "つづみ", Romaji: "tsuzumi", Meaning: "drum", Freq: 46, Simplified: "", Examples: "鼗 鼘"},
	&Radical{Num: 208, Rune: "鼠", AltRune: "", Strokes: 13, Pinyin: "shǔ", Hiragana: "ねずみ", Romaji: "nezumi", Meaning: "rat, mouse", Freq: 92, Simplified: "", Examples: "鼢 鼣 鼤"},
	&Radical{Num: 209, Rune: "鼻", AltRune: "", Strokes: 14, Pinyin: "bí", Hiragana: "はな", Romaji: "hana", Meaning: "nose", Freq: 49, Simplified: "", Examples: "鼼 鼽 鼿"},
	&Radical{Num: 210, Rune: "齊", AltRune: "", Strokes: 14, Pinyin: "qí", Hiragana: "せい", Romaji: "sei", Meaning: "even, uniformly", Freq: 18, Simplified: "齐", Examples: "齋 齏 齏"},
	&Radical{Num: 211, Rune: "齒", AltRune: "", Strokes: 15, Pinyin: "chǐ", Hiragana: "は", Romaji: "ha", Meaning: "tooth, molar", Freq: 162, Simplified: "齿", Examples: "齡 齠 齗"},
	&Radical{Num: 212, Rune: "龍", AltRune: "", Strokes: 16, Pinyin: "lóng", Hiragana: "りゅう", Romaji: "ryū", Meaning: "dragon", Freq: 14, Simplified: "龙", Examples: "龖 龘"},
	&Radical{Num: 213, Rune: "龜", AltRune: "", Strokes: 16, Pinyin: "guī", Hiragana: "かめ", Romaji: "kame", Meaning: "turtle, tortoise", Freq: 24, Simplified: "龟", Examples: "龝"},
	&Radical{Num: 214, Rune: "龠", AltRune: "", Strokes: 17, Pinyin: "yuè", Hiragana: "やく", Romaji: "yaku", Meaning: "flute", Freq: 19, Simplified: "", Examples: "龣 龤"},
}
