// generated by `usagen usagen`; DO NOT EDIT

//    Usage: usagen [OPTION]... CMD
//    Generate usage documentation for a given command.
//
//    Flags:
//      -o string
//        	Output path. (default "z_usage.go")
package main
