// Generated by `usagen usagen`; DO NOT EDIT.

//    Generate usage documentation for a given command.
//
//    Usage:
//
//    	usagen [OPTION]... CMD
//
//    Flags:
//
//      -o string
//        	output path
package main
